package com.eventplus.domain.organizer;

public enum BusinessType {
    PRIVATE_COMPANY,
    STARTUP,
    EVENT_AGENCY,
    EDUCATIONAL_INSTITUTION,
    GOVERNMENT_AGENCY,
    NONPROFIT_ORGANIZATION,
    ASSOCIATION,
    NGO,
    CULTURAL_INSTITUTION,
    SPORTS_ORGANIZATION,
    RELIGIOUS_INSTITUTION,
    HEALTHCARE_INSTITUTION,
    COOPERATIVE,
    FOUNDATION,
    PROFESSIONAL_ASSOCIATION,
    OTHER
}
